[package]
name = "sor_logparser"
version = "1.1.0"
authors = ["Shirley Chung <shirley@mail.kway.com.tw>"]
edition = "2021"

[features]
default = []
gui = ["dep:slint", "dep:rfd", "dep:regex"]

[dependencies]
structopt = "*"
encoding  = "*"
chrono    = "*"
slint = { version = "1.5.1", optional = true }
rfd = { version = "0.14.1", optional = true }
regex = { version = "1", optional = true }
